baseURL = "https://redhat-developer.github.io/rhd-frontend/"
languageCode = "en-us"
title = "RHD Front-end Code and Documentation"
theme = "rhd-docs"
publishDir = "../../docs"
canonifyURLs = true
disableFastRender = true

[params]
    Minify = true

[module]

    [[module.mounts]]
        source = "../data"
        target = "data"

    [[module.mounts]]
        source = "../styles"
        target = "assets/sass"
    
    [[module.mounts]]
        source = "../../dist/js"
        target = "assets/js"