version: 2

executors:
  node:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: 'npm install --no-package-lock'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run Tests
          command: npm test
      - store_artifacts:
          path: 'src/tests/unit/report/unit-test-report.html'
          prefix: tests
      - store_test_results:
          path: 'src/tests/unit/report/unit-test-report.html'