version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm'
      - run:
          name: Add fontawesome
          command: 'sudo npm config set "@fortawesome:registry" https://npm.fontawesome.com/ && \
              sudo npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_TOKEN'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: 'npm install --no-package-lock'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run Tests
          command: 'CHROME_BIN=/usr/bin/google-chrome && npm test'
      - store_artifacts:
          path: 'src/tests/unit/report/unit-test-report.html'
          prefix: tests
      - store_test_results:
          path: 'src/tests/unit/report/unit-test-report.xml'