version: 2

executors:
  node:
    docker:
      - image: circleci/node:latest-browser

jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run: #STABLE
          name: Install Chromedriver latest version
          command: |
            sudo apt-get update
            sudo apt-get install lsb-release libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      - run:
          name: Update npm
          command: 'sudo npm install -g npm'
      - run:
          name: Add npmrc
          command: "echo $'@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=$FONTAWESOME_TOKEN' >.npmrc"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: 'npm install --no-package-lock'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run Tests
          command: 'CHROME_BIN=/usr/bin/google-chrome && npm test'
      - store_artifacts:
          path: 'src/tests/unit/report/unit-test-report.html'
          prefix: tests
      - store_test_results:
          path: 'src/tests/unit/report/unit-test-report.html'