version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:latest

orbs:
  nodeorb: circleci/node@0.0.8

jobs:
  test:
    executor: node
    steps:
      - checkout
      - nodeorb/install-package-manager:
          npm: true
      - run:
          name: Install npm
          command: 'npm install --no-package-lock'
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run Tests
          command: npm test
      - store_artifacts:
          path: 'src/tests/unit/report/unit-test-report.html'
          prefix: tests